### PR TITLE
Update 00_overview.md

### PR DESCRIPTION
**Pull request by CalebCurry**
Basic docker example -- single command to launch client

### CODE REVIEW

**Comment by CalebCurry** [comment]
To elaborate, the goal of this is to give the least needed to get an API running with just docker installed. This is designed to be an alternative for local API testing compared to running snarkos.
The command should only require docker installed

**Review by d0cd — APPROVED** [review]
LGTM!

**Review by aharshbe — APPROVED** [review]
Looks great; thanks for the hard work @CalebCurry.

**Comment by aharshbe** [comment]
@CalebCurry, in the future, please keep in mind branch conventions per [this](https://github.com/AleoHQ/techops/blob/master/guides/branch-naming.md), but going to merge!

**Pull request merged**
