### PR TITLE
Add developer toolkit

### PR DESCRIPTION
**Pull request by moAlobaidi**
This PR tracks [PR](https://github.com/AleoHQ/aleo-docs/pull/243) and closes this [issue](https://github.com/AleoHQ/techops/issues/83).

### CODE REVIEW

**Comment by aharshbe** [comment]
The downloadable `.pkg` throws a MacOS error because it's not signed. I created an Apple Developer Account to fix this problem (we need to sign our packages with a valid cert, which requires an account). It's currently pending and says it could take up to 48 hours to approve.

When it's approved, I'll update this PR.

Ref: 
image
image

**Comment by moAlobaidi** [comment]
@aharshbe Any updates on Leo pkg signing approval?

**Review by aharshbe — APPROVED** [review]
This is good. @collinc97 feel free to merge this as soon as you upload the latest package I generated with the Apple sig.
- For those curious, I stored the utility script for how I generate signed packages [here](https://github.com/AleoHQ/techops/blob/master/internal-tools/utility-scripts/create_and_sign_package.sh).
- We are still waiting on Apple to switch our account to org. Once that happens, I'll update the script mentioned above.

**Comment by aharshbe** [comment]
Hey @moAlobaidi this is on me. We don't want to upload the .pkg yet because there will be a new release shortly. I'm going to change it to point folks to github.com/aleohq/leo/releases/latest and then copy this for when we do want to add the .pkg links.

**Review by aharshbe — APPROVED** [review]

**Comment by moAlobaidi** [comment]
@aharshbe Amazing, hyped to get this across the finish line 🏁

**Comment by aharshbe** [comment]
@collinc97 ready for your review when you have a moment 🙂

**Review by collinc97 — APPROVED** [review]

**Comment by collinc97** [comment]
LGTM I will create the branch on `aleo-docs`

**Comment by aharshbe** [comment]
@collinc97 noticed a broken link, which I fixed with [this PR](https://github.com/AleoHQ/welcome/pull/279).

**Pull request merged**
